ev.event_id, 
					ev.name, 
					DATE_FORMAT(ev.start_time, '%e') AS 'day',
					DATE_FORMAT(ev.start_time, '%Y') AS 'year',
					DATE_FORMAT(ev.start_time, '%k') AS 'hh',
					DATE_FORMAT(ev.start_time, '%i') AS 'mm',
					DATE_FORMAT(ev.end_time, '%e') AS 'end_day',
					DATE_FORMAT(ev.end_time, '%Y') AS 'end_year',
					DATE_FORMAT(ev.end_time, '%k') AS 'end_hh',
					DATE_FORMAT(ev.end_time, '%i') AS 'end_mm',
					ev.start_date,
					rec.end_date,
					ev.start_time,
					ev.end_time,
					ev.notes, 
					ev.rsvp,
					ev.location_id, 
					ev.contactperson_id,
					rec.interval,
					rec.byweekno,
					rec.freq,
					rec.byday,
					rec.recurrence_id

			name, 
				DATE_FORMAT(ev.start_date, '%Y-%m-%e') AS 'date', 
				DATE_FORMAT(ev.start_date, '%e') AS 'day',   
				DATE_FORMAT(ev.start_date, '%m') AS 'month',
				DATE_FORMAT(ev.start_date, '%Y') AS 'year',
				DATE_FORMAT(ev.start_time, '%k') AS 'hh',
				DATE_FORMAT(ev.start_time, '%i') AS 'mm',
				DATE_FORMAT(ev.start_time, '%h:%i%p') AS 'start_12h_time', 
				DATE_FORMAT(ev.start_time, '%H:%i') AS 'start_24h_time', 
				DATE_FORMAT(ev.end_time, '%Y-%m-%e') AS 'end_date', 
				DATE_FORMAT(ev.end_time, '%e') AS 'end_day',        
				DATE_FORMAT(ev.end_time, '%m') AS 'end_month',  
				DATE_FORMAT(ev.end_time, '%Y') AS 'end_year',
				DATE_FORMAT(ev.end_time, '%k') AS 'end_hh',
				DATE_FORMAT(ev.end_time, '%i') AS 'end_mm',
				DATE_FORMAT(ev.end_time, '%h:%i%p') AS 'end_12h_time', 
				DATE_FORMAT(ev.end_time, '%H:%i') AS 'end_24h_time',   
			 	ev.start_date,
				rec.end_date,
				ev.start_time,
				ev.end_time,
				ev.notes,
				ev.rsvp,
				ev.seats,
				rec.recurrence_id, 
				ev.location_id,
				ev.contactperson_id,
				rec.interval,
				rec.byweekno,
				rec.freq,
				rec.byday,
				rec.recurrence_id		
				
				
				
				